[platformio]
default_envs = lolin32
src_dir = firmware
data_dir = firmware/web

[env:lolin32]
platform = espressif32
board = lolin32
framework = arduino

; Bluepad32 custom framework override reference:
; platform_packages =
;   framework-arduinoespressif32 @ https://github.com/maxgerhardt/pio-framework-bluepad32/releases/download/4.1.0/framework-arduinoespressif32-bluepad32-4.1.0.tar.gz

monitor_speed = 115200
upload_speed = 921600
board_build.filesystem = littlefs
lib_ldf_mode = deep+

build_flags =
  -DCORE_DEBUG_LEVEL=3
  -Wall

lib_deps =
  me-no-dev/AsyncTCP @ ^1.1.1
  https://github.com/me-no-dev/ESPAsyncWebServer.git
  adafruit/DHT sensor library @ ^1.4.6
  adafruit/Adafruit Unified Sensor @ ^1.1.14
  bblanchon/ArduinoJson @ ^6.21.5
  adafruit/Adafruit NeoPixel @ ^1.12.0
